name: focusedinvesting
favicon: null
layout_spectrum: 1
typography_spectrum: 0.29466
title: 'Focused Investing: we manage money to help people achieve dreams!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c5c99'
    - '#93c7f6'
    - '#558ed5'
    - '#2a2a2a'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
